### ISSUE TITLE
Webpage  have not title tag

### ISSUE THREAD

**Issue by kittinan** [tupleblog/generate-thai-lyrics#6]
We need title tag for the web page

**Comment by titipata** [comment]
Kukkik AI แต่งเพลง?

**Comment by kittinan** [comment]
> Kukkik AI แต่งเพลง?

:+1: :+1:  :+1:

**Comment by kittinan** [comment]
Fixed 7f9dab3fa25c2f349d01de6f803fe03ad44f54c1
